### ISSUE TITLE
npm start doesn't work on Windows

### ISSUE THREAD

**Issue by hipertracker** [cerebral/cerebral-boilerplate-universal#1]
For Windows 7 Enterprise SP1

```
C:\home\cerebral-boilerplate-universal>node -v
v5.6.0

C:\home\cerebral-boilerplate-universal>npm start

> cerebral-boilerplate@0.1.0 prestart C:\home\cerebral-boilerplate-universal
> npm run build


> cerebral-boilerplate@0.1.0 build C:\home\cerebral-boilerplate-universal
> npm run build:client && npm run build:server


> cerebral-boilerplate@0.1.0 build:client C:\home\cerebral-boilerplate-universal
> rimraf dist && cross-env NODE_ENV=production webpack --config ./webpack.production.config.js --progress --profile --colors

2532ms build modules
6ms seal
3ms optimize
55ms build modules
7ms hashing
16ms create chunk assets
3025ms additional chunk assets
1ms optimize chunk assets
0ms optimize assets
20ms emit
Hash: 5263cf398faf6ee1da83
Version: webpack 1.12.13
Time: 5687ms
             Asset      Size  Chunks             Chunk Names
           main.js    232 kB       0  [emitted]  main
        styles.css  50 bytes       0  [emitted]  main
webpack.stats.json   0 bytes          [emitted]
   [0] multi main 28 bytes {0} [built]
       factory:0ms building:1ms = 1ms
    + 227 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules

> cerebral-boilerplate@0.1.0 build:server C:\home\cerebral-boilerplate-universal
> cross-env NODE_ENV=production webpack --config ./webpack.server.production.config.js --progress --profile --colors

2196ms build modules
3ms seal
7ms optimize
6ms hashing
14ms create chunk assets
2ms additional chunk assets
0ms optimize chunk assets
1ms optimize assets
14ms emit
Hash: 8d49382879e26168c44b
Version: webpack 1.12.13
Time: 2283ms
          Asset    Size  Chunks             Chunk Names
server_build.js  649 kB       0  [emitted]  main
    + 163 hidden modules

> cerebral-boilerplate@0.1.0 start C:\home\cerebral-boilerplate-universal
> node server_build

==> � Listening on port 3000. Open up http://0.0.0.0:3000/ in your browser.
Unhandled rejection Error: invalid argument
    at pathToArray (C:\home\cerebral-boilerplate-universal\node_modules\memory-fs\lib\MemoryFileSystem.js:44:10)
    at MemoryFileSystem.mkdirpSync (C:\home\cerebral-boilerplate-universal\node_modules\memory-fs\lib\MemoryFileSystem.js:139:13)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (C:\home\cerebral-boilerplate-universal\node_modules\memory-fs\lib\MemoryFileSystem.js:279:34)
    at Compiler.<anonymous> (C:\home\cerebral-boilerplate-universal\node_modules\webpack\lib\Compiler.js:229:25)
    at Compiler.next (C:\home\cerebral-boilerplate-universal\node_modules\tapable\lib\Tapable.js:67:11)
    at C:\home\cerebral-boilerplate-universal\node_modules\html-webpack-plugin\index.js:155:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Compiler.<anonymous> (C:\home\cerebral-boilerplate-universal\node_modules\html-webpack-plugin\index.js:154:15)
    at Compiler.applyPluginsAsync (C:\home\cerebral-boilerplate-universal\node_modules\tapable\lib\Tapable.js:71:13)
    at Compiler.emitAssets (C:\home\cerebral-boilerplate-universal\node_modules\webpack\lib\Compiler.js:226:7)
    at Watching.<anonymous> (C:\home\cerebral-boilerplate-universal\node_modules\webpack\lib\Compiler.js:54:18)
    at C:\home\cerebral-boilerplate-universal\node_modules\webpack\lib\Compiler.js:403:12
    at Compiler.next (C:\home\cerebral-boilerplate-universal\node_modules\tapable\lib\Tapable.js:67:11)
    at Compiler.<anonymous> (C:\home\cerebral-boilerplate-universal\node_modules\webpack\lib\CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (C:\home\cerebral-boilerplate-universal\node_modules\tapable\lib\Tapable.js:71:13)
    at Compiler.<anonymous> (C:\home\cerebral-boilerplate-universal\node_modules\webpack\lib\Compiler.js:400:9)
    at Compilation.<anonymous> (C:\home\cerebral-boilerplate-universal\node_modules\webpack\lib\Compilation.js:577:13)
    at Compilation.applyPluginsAsync (C:\home\cerebral-boilerplate-universal\node_modules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> (C:\home\cerebral-boilerplate-universal\node_modules\webpack\lib\Compilation.js:572:10)
    at Compilation.applyPluginsAsync (C:\home\cerebral-boilerplate-universal\node_modules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> (C:\home\cerebral-boilerplate-universal\node_modules\webpack\lib\Compilation.js:567:9)
    at Compilation.next (C:\home\cerebral-boilerplate-universal\node_modules\tapable\lib\Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (C:\home\cerebral-boilerplate-universal\node_modules\extract-text-webpack-plugin\index.js:303:4)
    at Compilation.applyPluginsAsync (C:\home\cerebral-boilerplate-universal\node_modules\tapable\lib\Tapable.js:71:13)
    at Compilation.<anonymous> (C:\home\cerebral-boilerplate-universal\node_modules\webpack\lib\Compilation.js:563:8)
```

**Comment by hipertracker** [comment]
The same on Windows 10

```
C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal>node -v
v5.6.0


C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal>npm install
...
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7



C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal>npm start

> cerebral-boilerplate@0.1.0 prestart C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal
> npm run build


> cerebral-boilerplate@0.1.0 build C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal
> npm run build:client && npm run build:server


> cerebral-boilerplate@0.1.0 build:client C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal
> rimraf dist && cross-env NODE_ENV=production webpack --config ./webpack.production.config.js --progress --profile --colors

2678ms build modules
0ms seal
0ms optimize
53ms build modules
15ms hashing
16ms create chunk assets
2702ms additional chunk assets
0ms optimize chunk assets
15ms optimize assets
69ms emit
Hash: 9b9f064d83db40cff2a4
Version: webpack 1.12.13
Time: 5582ms
             Asset      Size  Chunks             Chunk Names
           main.js    232 kB       0  [emitted]  main
        styles.css  50 bytes       0  [emitted]  main
webpack.stats.json   0 bytes          [emitted]
   [0] multi main 28 bytes {0} [built]
       factory:1ms building:3ms = 4ms
    + 227 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules

> cerebral-boilerplate@0.1.0 build:server C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal
> cross-env NODE_ENV=production webpack --config ./webpack.server.production.config.js --progress --profile --colors

2464ms build modules
0ms seal
15ms optimize
0ms hashing
32ms create chunk assets
0ms additional chunk assets
0ms optimize chunk assets
0ms optimize assets
53ms emit
Hash: 8d49382879e26168c44b
Version: webpack 1.12.13
Time: 2602ms
          Asset    Size  Chunks             Chunk Names
server_build.js  649 kB       0  [emitted]  main
    + 163 hidden modules

> cerebral-boilerplate@0.1.0 start C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal
> node server_build

==> � Listening on port 3000. Open up http://0.0.0.0:3000/ in your browser.
Unhandled rejection Error: invalid argument
    at pathToArray (C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\memory-fs\lib\MemoryFileSystem.js:44:10)
    at MemoryFileSystem.mkdirpSync (C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\memory-fs\lib\MemoryFileSystem.js:139:13)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\memory-fs\lib\MemoryFileSystem.js:279:34)
    at Compiler.<anonymous> (C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\webpack\lib\Compiler.js:229:25)
    at Compiler.next (C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\tapable\lib\Tapable.js:67:11)
    at C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\html-webpack-plugin\index.js:155:9
    at PassThroughHandlerContext.finallyHandler (C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\bluebird\js\release\finally.js:55:23)
    at PassThroughHandlerContext.tryCatcher (C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\bluebird\js\release\promise.js:497:31)
    at Promise._settlePromise (C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\bluebird\js\release\promise.js:555:18)
    at Promise._settlePromise0 (C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\bluebird\js\release\promise.js:600:10)
    at Promise._settlePromises (C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\bluebird\js\release\async.js:125:16)
    at Async._drainQueues (C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\bluebird\js\release\async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\hipertracker\Desktop\cerebral-boilerplate-universal\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

webpack: wait until bundle finished: /green
```

**Comment by christianalfoni** [comment]
I believe this is fixed now?
